training:
  batch_size: 4
  lr: 0.003
  seed: 42
  val_every_step: 2000
  lr_warmup_steps: 2000
  lr_decay_until_steps: ${.num_steps}
  lr_decay_factor: 0.001
  weight_decay: 0.1
  num_steps: 1000000
  device: cuda
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true

model:
  num_blocks: 16
  embedding_dim: 768
  mlstm_block:
    mlstm:
      num_heads: 4
  slstm_block: {}
  slstm_at: []
  context_length: ${dataset.kwargs.context_length}
  vocab_size: ${dataset.kwargs.vocab_size}

dataset:
  data_dir: "D:/Capstone/telugu_dataset_corpus/test_data" #" # telugu_text
  block_size: 512
  batch_size: 4
  name: form_language
  kwargs:
    synth_lang_type: parity
    vocab_size: 200002
    seed: 1
    enable_mask: true
    context_length: 512
    min_sequence_length: 3
    max_sequence_length: 40
    count:
      train: 5120000
      validation: 8192
      test: 8192
    subpar:
      validation:
        min_sequence_length: 40
        max_sequence_length: 256
      test:
        min_sequence_length: 40
        max_sequence_length: 256
